version: '2'
services:
    webserver:
        image: jbfavre/airflow-light:1.7.1.3
        restart: always
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        ports:
            - "8080:8080"
        command: webserver

    flower:
        image: jbfavre/airflow-light:1.7.1.3
        restart: always
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: jbfavre/airflow-light:1.7.1.3
        restart: always
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        command: scheduler -n 5

    worker:
        image: jbfavre/airflow-light:1.7.1.3
        restart: always
        # volumes:
        #     - /localpath/to/dags:/usr/local/airflow/dags
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        command: worker
